#!/bin/bash

IPTABLES=`which iptables`

#reset policy
set_policy() {
# set default policies.
	$IPTABLES -P INPUT ACCEPT 
        $IPTABLES -P OUTPUT ACCEPT
        $IPTABLES -P FORWARD ACCEPT 
}
#flush rulesets
set_default() {
	$IPTABLES -F 
}

# run stuff
set_policy
set_default


